title: Blog of Jakub Hladik
author: Jakub Hladik
email: lounge-gazer-0o@icloud.com
description: A computer engineer interested in everything.
baseurl: ""
url: "https://jhladik.github.io"
github_username: jhladik
theme: minima
google_analytics: G-ZEENHPSMM2
plugins:
  - jekyll-feed
  - jekyll-seo-tag